import { opacity } from "@xstyled/emotion";

const buttons = {
  none: {
    padding: "0px",
    margin: "0px",
    border: "none",
    background: "transparent",
  },
  btnBig: {
    cursor: "pointer",
  },
  primaryLarge: {
    backgroundColor: "green.1000",
    fontSize: "1.15rem",
    fontWeight: 600,
    color: "green.100",
    padding: "0.75rem 1rem",
    borderRadius: "0.85rem",
    ":hover": {
      backgroundColor: "green.1100",
      borderColor: "green.1200",
    },
  },
  secondaryLarge: {
    backgroundColor: "gray.100",
    fontSize: "1.15rem",
    fontWeight: 600,
    color: "green.1200",
    padding: "0.75rem 1rem",
    borderRadius: "0.75rem",
    border: "solid 1px",
    borderColor: "green.900",
    "&:hover": {
      backgroundColor: "green.200",
      borderColor: "green.a500",
      color: "green.700 !important",
    },
  },
  tertiaryLarge: {
    backgroundColor: "gray.100",
    fontSize: "1.15rem",
    fontWeight: 600,
    color: "gray.1200",
    padding: "0.75rem 1rem",
    borderRadius: "0.75rem",
    "&:hover": {
      color: "green.800 !important",
    },
  },
  primary: {
    backgroundColor: "primary",
    color: "#fff",
    border: "1px solid",
    borderColor: "primary",
    borderRadius: "4px",
    padding: "8px 16px",
    fontWeight: "heading",
    fontSize: "sm",
    fontFamily: "body",
    ":hover": {
      backgroundColor: "green.1000",
      borderColor: "#197231",
    },
    ":disabled": {
      backgroundColor: "#E4E9EF",
      borderColor: "#E4E9EF",
      color: "gray.200",
    },
  },

  secondary: {
    cursor: "pointer",
    backgroundColor: "gray.200",
    color: "gray.1200",
    border: "1px solid",
    borderColor: "gray.500",
    borderRadius: "6px",
    padding: "8px 12px",
    fontWeight: 600,
    fontSize: "sm",
    fontFamily: "body",
    svg: {
      opacity: 0.5,
    },
    ":disabled": {
      color: "gray.600",
      cursor: "not-allowed",
      pointerEvents: "auto !important",
    },
    ":hover": {
      backgroundColor: "gray.400",
      borderColor: "gray.500",
    },
  },
  ghostinline: {
    display: "flex",
    bg: "gray.200",
    border: "solid 1px",
    borderColor: "gray.700",
    padding: "6px 9px",
    fontWeight: "heading",
    svg: {
      opacity: "0.6",
    },
    fontSize: "sm",
    fontFamily: "body",
    borderRadius: "6px",
    color: "gray.1100",
    ":hover": {
      bg: "green.300",
      color: "gray.200",
    },
    ":disabled": {
      color: "gray.900",
      bg: "neutral.300",
    },
  },
  ghost: {
    background: "transparent",
    border: "none",
    padding: "8px 16px",
    fontWeight: "heading",
    fontSize: "sm",
    fontFamily: "body",
    color: "text",
    ":hover": {
      backgroundColor: "#F0F2F5",
    },
    ":disabled": {
      color: "gray.900",
      bg: "neutral.300",
    },
  },
  buttonPrimary: {
    cursor: "pointer",
    borderRadius: "4px",
    p: "8px 16px",
    ":disabled": {
      cursor: "default",
      color: "gray.200",
      bg: "neutral.200",
    },
    color: "#fff",
    backgroundColor: "primary.9",
  },
  buttonSecondary: {
    variant: "buttons.buttonPrimary",
    color: "text",
    bg: "neutral.200",
  },
  buttonPrimarySmall: {
    variant: "buttons.buttonPrimary",
    fontSize: "sm",
  },
  delete: {
    variant: "buttons.buttonPrimary",
    bg: "red.700",
  },
  cancel: {
    variant: "buttons.buttonPrimary",
    bg: "neutral.300",
    color: "gray.900",
  },
  googleLogin: {
    fontWeight: "bold",
    color: "gray.800",
    background: "none",
    border: "1px solid",
    borderColor: "border",
    borderRadius: "4px",
    py: "9px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "16px",
    cursor: "pointer",
    width: "100%",
    ":hover": {
      bg: "transparent",
    },
    ":focus": {
      bg: "transparent",
    },
  },
  download: {
    bg: "gray.200",
    textTransform: "capitalize",
  },
  btnPrimary: {
    variant: "buttons.btnBig",
    bg: "primary.9",
    color: "primary.2",
    fontSize: "sm",
    borderRadius: 6,
    cursor: "pointer",
    px: 3,
    py: 2,
    ":hover": {
      bg: "green.800",
      borderColor: "border",
    },
  },
  iconButton: {
    bg: "red.100",
  },
  btnMenu: {
    mr: 2,
    a: {
      textDecoration: "none",
      color: "text",
      py: 2,
      px: 1,
      width: "100%",
      "&.active": {
        background: "green.a200",
        // background: '#E2F7EA',
        color: "green.800",
        svg: {
          fill: "green.300",
        },
      },
      ":hover": {
        background: "green.a500",
        // background: '#E2F7EA',
      },
    },
  },
  btnSecondary: {
    variant: "buttons.btnPrimary",
    bg: "gray.100",
    cursor: "pointer",
    color: "gray.1200",
    fontSize: "sm",
    borderRadius: 6,
    border: "solid 1px",
    borderColor: "border",
    ":hover": {
      bg: "gray.200",
      color: "gray.900",
    },
  },
  btnSecondaryInline: {
    variant: "buttons.btnPrimary",
    bg: "white",
    cursor: "pointer",
    color: "gray.1200",
    fontSize: "sm",
    borderRadius: 6,
    display: "flex",
    paddingTop: "6px",
    paddingBottom: "6px",
    alignItems: "center",
    paddingLeft: "12px",
    paddingRight: "12px",
    marginTop: "4px",
    marginBottom: "4px",
    border: "solid 1px",
    borderColor: "border",
    ":hover": {
      bg: "gray.200",
      color: "gray.1200",
    },
  },
  btnPrimaryInline: {
    variant: "buttons.btnPrimary",
    bg: "green.1100",
    cursor: "pointer",
    color: "green.100",
    fontSize: "sm",
    borderRadius: 6,
    display: "flex",
    paddingTop: "4px",
    paddingBottom: "4px",
    alignItems: "center",
    paddingLeft: "12px",
    paddingRight: "12px",
    marginTop: "4px",
    marginBottom: "4px",
    py: 1,
    border: "solid 1px",
    borderColor: "border",
    ":hover": {
      bg: "gray.200",
      color: "gray.900",
    },
  },
  btnAction: {
    variant: "buttons.btnBig",
    bg: "gray.900",
    color: "gray.200",
    borderColor: "border",
    ":hover": {
      bg: "gray.1000",
      color: "gray.100",
    },
  },
  btnSmall: {
    cursor: "pointer",
    variant: "buttons.btnSecondary",
    fontSize: "xxs",
    p: 1,
    px: 2,
  },
  btnIcon: {
    variant: "buttons.btnSecondary",
    bg: "gray.100",
    color: "gray.1100",
    borderColor: "gray.300",
    ":hover": {
      bg: "gray.300",
      color: "gray.1200",
    },
    px: 2,
    py: "3px",
    pt: "6px",
  },
  btnPrimaryLarge: {
    variant: "buttons.btnBig",
    fontSize: "xs",
    p: 2,
    px: 3,
    border: 0,
  },
  base: {
    cursor: "pointer",
    bg: "transparent",
    color: "gray.1000",
  },
  button: {
    border: "solid 1px",
    borderColor: "border",
    p: 1,
    mt: 3,
    lineHeight: 0,
    svg: { fill: "text" },
    bg: "gray.200",
    cursor: "pointer",
  },
  buttonApproval: {
    ml: 3,
    bg: "neutral.100",
    fontSize: "xxs",
    fontWeight: 600,
    color: "gray.800",
    border: "solid 1px ",
    borderRadius: "6px",
    borderColor: "gray.100",
    fontFamily: "heading",
    textTransform: "uppercase",
    cursor: "pointer",
    "&:hover": {
      color: "gray.900",
      bg: "neutral.200",
    },
  },
  btnDelete: {
    background: "none",
    cursor: "pointer",
    pr: "0px",
    pl: "28px",
    display: "flex",
  },
  btnLarge: {
    // variant: 'buttons.btnBig',
    fontSize: "base",
    p: 2,
    px: 3,
    border: 0,
  },
};

export default buttons;
