const layout = {
  dialog: {
    bg: "neutral.100",
    position: "fixed",
    inset: "20ch",
    zIndex: 50,
    margin: "auto",
    display: "flex",
    height: "fit-content",
    maxHeight: "calc(100vh - 2 * 0.75rem)",
    flexDirection: "column",
    gap: "1rem",
    overflow: "auto",
    borderRadius: "4px",
    padding: 0,
    color: "hsl(204 10% 10%)",
    boxShadow: "0 25px 50px -12px rgb(0 0 0 / 0.25)",
    transformOrigin: "center",
    opacity: 1,
    transitionProperty: "opacity, transform",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDuration: "150ms",
    transform: "scale(0.95)",
    maxWidth: "fit-content",
  },
  pageFrame: {
    bg: "background",
    p: 4,
    height: "calc(100vh - 72px)",
    overflow: "scroll",
    "::-webkit-scrollbar": {
      width: "8px",
    },
    "::-webkit-scrollbar-thumb": {
      backgroundColor: "#B8B3B1",
      borderRadius: "10px",
    },
    "::-webkit-scrollbar-track": {
      backgroundColor: "transparent",
    },
    "::-webkit-scrollbar-button": {
      display: "none",
    },
  },

  menu: {
    height: "auto",
    minWidth: "155px",
    width: "fit-content",
    position: "absolute",
    top: 0,
    left: 0,
    zIndex: "50",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    borderRadius: "4px",
    backgroundColor: "white",
    padding: "8px",
    color: "hsl(204 10% 10%)",
    boxShadow: `2px 3px 14px 0px rgba(0, 0, 0, 0.16)`,
  },
  w100: {
    width: "100%",
  },
  header: {
    borderBottom: "solid 1px",
    borderColor: "border",
    paddingBottom: 2,
    paddingTop: 2,
    paddingLeft: 2,
  },
};

export default layout;
