import React, { useEffect, useState } from 'react';
import { Box, Text, Flex } from 'rebass';
import Link from './NavLink';
import { Plus } from './Icons';
import { loadEntity } from '../utils/models';
import { useStoreState } from 'easy-peasy';

// Generated by https://quicktype.io

export interface Pipelines {
  total_pages: number;
  total_entries: number;
  pipelines: Pipeline[];
  page_number: number;
}

export interface Pipeline {
  updated_at: string;
  name: string;
  inserted_at: string;
  id: string;
  api_route: string;
  stages: any;
}

const ItemField = (props: any) => {
  // const deletePipeline = (id: string, token: string) => {
  //   deleteEntity(`pipelines/${id}`, token);
  // };

  return (
    <Box
      variant="boxy"
      width={1 / 4}
      key={props.id}
      p={3}
      sx={{ bg: '#fff', borderBottom: 'solid 1px #eee', borderRadius: '3px' }}>
      <Link href={`/pipelines/run/${props.id}`}>
        <Text fontSize={1} fontWeight="bold">
          {props.name}
        </Text>
        <Text fontSize={0} pt={1} color="grey">
          Desc
        </Text>
      </Link>
    </Box>
  );
};

const Form = () => {
  const token = useStoreState(state => state.auth.token);

  const [contents, setContents] = useState<Array<Pipeline>>([]);

  const loadDataSuccess = (data: any) => {
    const res: Pipeline[] = data.pipelines;
    setContents(res);
  };

  const loadData = (t: string) => {
    loadEntity(t, 'pipelines', loadDataSuccess);
  };

  useEffect(() => {
    if (token) {
      loadData(token);
    }
  }, [token]);

  return (
    <Box py={3} width={1} mt={4}>
      <Flex>
        <Text fontSize={2} mb={3}>
          All Pipelines
        </Text>
        <Box ml="auto">
          <Link href="/pipelines/new" icon={<Plus />}>
            <Text>New</Text>
          </Link>
        </Box>
      </Flex>
      <Box mx={0} mb={3} width={1}>
        <Box>
          {contents &&
            contents.length > 0 &&
            contents.map((m: any) => (
              <ItemField
                key={m.id}
                {...m}
                t="eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ3cmFmdF9kb2MiLCJleHAiOjE1OTE5MTcwOTQsImlhdCI6MTU4OTQ5Nzg5NCwiaXNzIjoid3JhZnRfZG9jIiwianRpIjoiZjExYTM2ODQtNjMxZi00Yjg0LTliOGEtMmY4OWMzMzlkM2ExIiwibmJmIjoxNTg5NDk3ODkzLCJzdWIiOiJhZG1pbkB3cmFmdGRvY3MuY29tIiwidHlwIjoiYWNjZXNzIn0.Sripy5ul5bW6xy_5ebxdPq4WihBIntde3Aq4kcWDE5gCgZpFpKR22hQtq_Y9ZWT1ARTXecMDxeQ-I7w30IAPLQ"
              />
            ))}
        </Box>
      </Box>
    </Box>
  );
};
export default Form;
