name: Vercel Production Deployment

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel \
            --token $VERCEL_TOKEN \
            --prod \
            --project ${{ secrets.VERCEL_PROJECT_ID }} \
            --org ${{ secrets.VERCEL_ORG_ID }}
